name: Build EXE
on: workflow_dispatch

jobs:
  BuildEXE:
    runs-on: windows-2022
    steps:
      - name: 01. Copy repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: | # Only copy specific folders to the container
            .github
            source

      - name: 02. Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 03. Create EXE
        shell: powershell
        run: |
          New-Item -ItemType Directory -Force -Verbose -Path "$Env:GITHUB_WORKSPACE\release"
          pip install pyinstaller
          pyinstaller --onefile "$Env:GITHUB_WORKSPACE\source\main.py" --name GLToolkit
          Move-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\dist\GLToolkit.exe" -Destination "$Env:GITHUB_WORKSPACE\release\GLToolkit.exe"

          echo "`n[i] Move 3rdparty folder"
          New-Item -ItemType Directory -Force -Verbose -Path "$Env:GITHUB_WORKSPACE\release\3rdparty"
          Move-Item -Verbose -Path "$Env:GITHUB_WORKSPACE\3rdparty\" -Destination "$Env:GITHUB_WORKSPACE\release\3rdparty\"

          echo "`n[i] Download Strawberry Perl"
          Invoke-WebRequest -Uri "https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/download/SP_5380_5361/strawberry-perl-5.38.0.1-64bit-portable.zip" -OutFile strawberry-perl.zip
          #Expand-Archive strawberry-perl.zip -DestinationPath "$Env:GITHUB_WORKSPACE\release\3rdparty\strawberry-perl"

      - name: 06. Publish EXE
        uses: actions/upload-artifact@v4
        with:
          name: GLToolkit
          path: ${{ github.workspace }}\release