name: Build EXE
on: workflow_dispatch

jobs:
  BuildEXE:
    runs-on: windows-2022
    steps:
      - name: 01. Copy repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: | # Only copy specific folders to the container
            .github
            source

      - name: 02. Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 03. Install pyinstaller
        shell: powershell
        run: |
          pip install pyinstaller

      - name: 04. Create EXE
        shell: powershell
        run: |
          pyinstaller --onefile "$Env:GITHUB_WORKSPACE\source\main.py" --name GLToolkit

      - name: 05. Check files
        shell: powershell
        run: |
          ls "$Env:GITHUB_WORKSPACE\dist"

      - name: 06. Publish EXE
        uses: actions/upload-artifact@v4
        with:
          name: GLToolkit
          path: ${{ github.workspace }}\dist